### PR TITLE
Add licenses of code used

### PR DESCRIPTION
**Pull request by CGDogan**
Our software needs to display legal licenses so now there's this small text, on clicked, below appears scrollable license text.

Screenshot 2024-03-02 at 19 49 45
Screenshot 2024-03-02 at 19 49 49

### CODE REVIEW

**Review by George-Ogden — CHANGES_REQUESTED** [review]
Do you think this can just open up the license in a new tab? Or have some way to hide it?

**Comment by CGDogan** [comment]
What do you mean by hide it? The text appears only when the user clicks on legal notices, and when he clicks on the license text, it disappears

**Comment by George-Ogden** [comment]
> What do you mean by hide it? The text appears only when the user clicks on legal notices, and when he clicks on the license text, it disappears

Sorry, the hiding isn't working for me

**Comment by CGDogan** [comment]
click on any character in the long text

**Comment by George-Ogden** [comment]
Can it also hide if you click on "legal notices" please? That seems more intuitive

**Comment by CGDogan** [comment]
good point, updated

**Review by George-Ogden — APPROVED** [review]

**Pull request merged**
