### PR TITLE
fix reset button not updating ui

### PR DESCRIPTION
**Pull request by CGDogan**
internet suggested using key, this is just a workaround

### CODE REVIEW

**Comment by CGDogan** [comment]
Set and invalid date range, click on reset, you'll see that the date isn't updated.

**Comment by CGDogan** [comment]
Of course, at 12

**Comment by CGDogan** [comment]
sorry for many commits, it's ready for review whenever you have time

**Comment by Hex27** [comment]
That's equivalent to just uuidv4(), that's already a unique ID

**Comment by CGDogan** [comment]
You're right, sorry I didn't keep my computer up to date with your changes, so rebasing solved it already.

**Pull request closed without merging**
