### PR TITLE
set fixes and cleanup

### PR DESCRIPTION
**Pull request by CGDogan**
- fix bugs, add tests, cleanup stored functions as they aren't needed
- remove unused code

### CODE REVIEW

**Comment by CGDogan** [comment]
Leonard this changes the species code to use an excludes set, I hope this works well for you?

**Comment by Hex27** [comment]
Hey, the panel sidebar is noticeably slower now, was there a heavy computation introduced into the species selector or the other selectors?

**Comment by Hex27** [comment]
Just profiled this, it appears to stem from a significant slowdown in recalculateFilteredData()

**Review by Hex27 — CHANGES_REQUESTED** [review]
Significant slowdown in recalculateFilteredData(), hold this change for now until the cause is found

**Comment by Hex27** [comment]
New call stack:
image

Old call stack:
image

**Comment by CGDogan** [comment]
Thank you for this, it'll actually be faster as I added nothing heavy so
there's a bug I hope to find out.

**Comment by Hex27** [comment]
I've figured out why. It's because SpeciesSelector is now performing a compound query against 3 columns.

In the old version, it will filter groups and endangerment status **before** passing a query to the panel. In the new version, it is filtering species, then groups, then endangerment. It is 3 times slower.

It was part of why I didn't want to invert SpeciesSelector

**Comment by CGDogan** [comment]
I found the problem dont revert thanks

**Review by Hex27 — APPROVED** [review]

**Pull request merged**
